name: CI/CD

on:
  push:
    branches: ["gege"]
  pull_request:
    branches: ["gege"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USER }}/whatsappassist:latest,${{ secrets.DOCKERHUB_USER }}/whatsappassist:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            sudo docker image prune -f
            sudo docker pull ${{ secrets.DOCKERHUB_USER }}/whatsappassist:latest
            sudo docker stop whatsappassist || true
            sudo docker rm whatsappassist || true
            sudo docker run -d -p 3000:3000 -v .wwebjs_auth:/app/.wwebjs_auth -v .wwebjs_cache:/app/.wwebjs_cache -v cache:/app/cache -v data:/app/data ${{ secrets.DOCKERHUB_USER }}/whatsappassist:latest
