name: Build and Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USER }}/yourapp:latest .
        docker push ${{ secrets.DOCKERHUB_USER }}/yourapp:latest

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USER }}/yourapp:latest
          docker stop yourapp || true
          docker rm yourapp || true
          docker run -d --name yourapp -p 80:80 ${{ secrets.DOCKERHUB_USER }}/yourapp:latest
